apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: eck-kibana
    releaseName: eck-kibana
    namespace: eck
    valuesFile: values.yaml
    version: 0.14.1
    repo: https://helm.elastic.co