version: 8.17.0
elasticsearchRef:
  name: eck-elasticsearch
  namespace: eck
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
  className: "nginx"
  pathType: ImplementationSpecific
  hosts:
    - host: kibana.loibis.com
      path: /
  tls:
    enabled: true
    secretName: kibana-tls