apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: eck-operator
    releaseName: eck-operator
    namespace: eck
    valuesFile: values.yaml
    version: 2.16.1
    repo: https://helm.elastic.co