apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kibana
    releaseName: kibana
    namespace: monitoring
    valuesFile: values.yaml
    repo: https://grafana.github.io/helm-charts