apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    repo: https://traefik.github.io/charts