ports:
  web:
    port: 8181
    expose: 
      default: true
    exposedPort: 8181
    protocol: TCP
  websecure:
    port: 8443
    expose: 
      default: true
    exposedPort: 8443
    protocol: TCP
  minecraft:
    port: 25565
    expose: 
      default: false
    exposedPort: 25565
    protocol: TCP
    tls:
      enabled: true    
additionalArguments:
  - "--entrypoints.minecraft.address=:25565"