entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"
  minecraft:
    address: ":25565"
additionalArguments:
  - --providers.kubernetescrd
experimental:
  plugins:
    kubernetescrd: true
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
crds:
  create: true