ports:
  web:
    port: 8181
    expose: 
      default: true
    exposedPort: 8181
    protocol: TCP
  websecure:
    port: 8443
    expose: 
      default: true
    exposedPort: 8443
    protocol: TCP
  minecraft:
    port: 25565
    protocol: TCP
    expose: true
    exposedPort: 25565
    tls:
      enabled: true
additionalArguments:
  - "--entrypoints.minecraft.address=:25565"
  - "--entrypoints.minecraft.transport.lifecyle.requestacceptgracetimeout=0s"
  - "--entrypoints.minecraft.forwardheaders.insecure=true"
  - "--entrypoints.minecraft.tls=true"
  