apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: elasticsearch
    releaseName: elasticsearch
    namespace: monitoring
    valuesFile: values.yaml
    repo: https://helm.elastic.co