apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: eck-elasticsearch
    releaseName: eck-elasticsearch
    namespace: eck
    valuesFile: values.yaml
    version: 0.14.1
    repo: https://helm.elastic.co