version: 8.17.0
nodeSets:
- name: default
  count: 1
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: local-path
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
  className: "nginx"
  pathType: ImplementationSpecific
  hosts:
    - host: elasticsearch.loibis.com
      path: /
  tls:
    enabled: true
    secretName: elasticsearch-tls